version: '3.10'
services:
  python:
    container_name: python
    build: ./src
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    container_name: postgresql
    image: postgres:14-alpine
    ports:
      - '5000:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_DB=marvel
volumes:
  postgres_data: